# Generated by Django 2.2 on 2020-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0007_auto_20201112_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.CharField(choices=[('1', '1 año'), ('2', '2 año'), ('3', '3 año'), ('4', '4 año'), ('5', '5 año'), ('6', '6 año'), ('7', '7 año')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(choices=[('°A', '°A'), ('°B', '°B'), ('°C', '°C')], max_length=10),
        ),
    ]
