# Generated by Django 2.2 on 2020-11-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0015_auto_20201122_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='persona_ptr',
        ),
        migrations.RemoveField(
            model_name='libroenventa',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
