# Generated by Django 2.2 on 2020-11-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0016_auto_20201125_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaDescargable',
            new_name='MaterialDescargable',
        ),
    ]
