# Generated by Django 2.2 on 2020-11-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0017_auto_20201126_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
