# Generated by Django 2.2 on 2020-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0002_auto_20201104_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
