# Generated by Django 2.2 on 2020-11-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0005_auto_20201104_1820'),
        ('bibliovirtual', '0002_auto_20201105_1950'),
    ]

    operations = [
    ]
