# Generated by Django 2.2 on 2020-11-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bibliovirtual', '0014_auto_20201112_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(choices=[('A', '°A'), ('B', '°B'), ('C', '°C')], max_length=10),
        ),
    ]
