# Generated by Django 2.2 on 2020-12-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliovirtual', '0019_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroenventa',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliovirtual.Alumno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.CharField(choices=[('1 año', '1ero'), ('2', '2do'), ('3', '3ero'), ('4', '4to'), ('5', '5to'), ('6', '6to'), ('7', '7mo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='materia',
            field=models.CharField(choices=[('Lengua', 'Lengua'), ('Biologia', 'Biologia'), ('Matematica', 'Matematica'), ('Ingles', 'Ingles'), ('Programacion', 'Programacion')], max_length=20),
        ),
    ]
